version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: farm4u_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: farm_manager_4u
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - farm4u_network

volumes:
  postgres_data:

networks:
  farm4u_network:
    driver: bridge
